"""channel_analytics.config.secrets — 自动生成 + 写 .env

命令:  channel-analytics init-secrets

行为:
  1. 读 .env(若不存在则从 .env.example 复制)
  2. 找到所有值 == "GENERATE-ON-FIRST-RUN" 的变量
  3. 用 secrets.token_urlsafe(48) 生成 64 字符随机串替换
  4. 写回 .env(保留其他注释与字段)
  5. 打印: "已生成 N 个密钥到 .env"

设计原则:
  - 不打印生成的密钥(只在第一次 .env 写入时存在)
  - 幂等:已存在的密钥不会被覆盖
  - 不会破坏 .env 的注释 / 空行
"""
from __future__ import annotations

import re
import secrets
import sys
from pathlib import Path

from channel_analytics.config.settings import PLACEHOLDER

ENV_PATH = Path(".env")
ENV_EXAMPLE = Path(".env.example")
GENERATED_MARK = "# auto-generated by channel-analytics init-secrets"

# 检测"key=value"行(忽略注释行)
KV_RE = re.compile(
    r"""^
    \s*
    (?P<key>[A-Z][A-Z0-9_]*)
    \s* = \s*
    (?P<val>.*?)
    \s*$
    """,
    re.VERBOSE | re.IGNORECASE,
)


def _load_env_lines() -> list[str]:
    if not ENV_PATH.exists():
        if not ENV_EXAMPLE.exists():
            print("ERROR: .env.example not found. Are you in the project root?", file=sys.stderr)
            sys.exit(1)
        print(f"INFO: .env not found, copying from {ENV_EXAMPLE}")
        ENV_PATH.write_text(ENV_EXAMPLE.read_text(encoding="utf-8"), encoding="utf-8")
    return ENV_PATH.read_text(encoding="utf-8").splitlines(keepends=False)


def _parse_kv(line: str) -> tuple[str, str] | None:
    if line.lstrip().startswith("#"):
        return None
    m = KV_RE.match(line)
    if not m:
        return None
    return m.group("key"), m.group("val")


def init_secrets() -> int:
    """扫描 .env,把所有 PLACEHOLDER 替换为随机 secret。返回替换数量。"""
    lines = _load_env_lines()
    new_lines: list[str] = []
    replaced = 0

    for line in lines:
        kv = _parse_kv(line)
        if kv is None:
            new_lines.append(line)
            continue
        key, val = kv
        if val == PLACEHOLDER:
            new_val = secrets.token_urlsafe(48)  # 64 字符 base64-urlsafe
            new_lines.append(f"{key}={new_val}  {GENERATED_MARK}")
            replaced += 1
        else:
            new_lines.append(line)

    if replaced == 0:
        print("OK: no placeholders found, .env already has real secrets")
        return 0

    ENV_PATH.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    # 把权限收紧(类 unix 才有意义,Windows 跳过)
    try:
        ENV_PATH.chmod(0o600)
    except OSError:
        pass

    print(f"OK: wrote {replaced} secret(s) to {ENV_PATH.resolve()}")
    print("    These values are NOT printed; back up .env to a password manager.")
    return replaced
